---
kind: pipeline
name: default


platform:
  os: linux
  arch: arm


steps:
- name: install and build
  image: node:12
  commands:
    - npm install hackmyresume -g
    - wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
    - tar xvf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
    - export PATH="`pwd`/wkhtmltox/bin:/usr/local/bin/"
    - hackmyresume build resume-FRESH/*.json resume-FRESH/options/writing.min.json to dist/resume.pdf --theme compact
    - hackmyresume build resume-FRESH/*.json to dist/resume.html --theme positive

- name: release to gh-pages
  image: node:12
  commands:
  - cp dist/resume.pdf one-page/resume-`date -I`.pdf
  - sed -e '/<head>/r gtag.head' dist/resume.html > index.html
  - sed -i -e "s/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}/`date -I`/g" pdf.html
  depends_on:
    - install and build

- name: push
  image: appleboy/drone-git-push
  settings:
    branch: master
    remote: git@github.com:jarronshih/jarronshih.github.io.git
    force: false
    commit: true
  depends_on:
    - release to gh-pages

trigger:
  branch:
  - master