sudo: required

services:
  - docker

before_install:
  - make build

script:
  - make all

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
