sudo: required

services:
  - docker

before_install:
  - if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "Deploy jarronshih/jarronshih.github.io" ; then echo "[skip] has been found, exiting" && exit 0 ; else echo "[skip travis] has not been found, continuing" ; fi
  - make build

script:
  - make all

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: master
  on:
    branch: master
